--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

-- Started on 2025-03-19 18:56:56

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 7 (class 2615 OID 16398)
-- Name: web; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA web;


ALTER SCHEMA web OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 222 (class 1259 OID 16417)
-- Name: partner; Type: TABLE; Schema: web; Owner: postgres
--

CREATE TABLE web.partner (
    id_partner integer NOT NULL,
    nome character varying NOT NULL,
    data_fondazione date,
    n_dipendenti integer,
    fatturato_annuo numeric DEFAULT 0,
    sede_id integer NOT NULL
);


ALTER TABLE web.partner OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16416)
-- Name: partner_id_partner_seq; Type: SEQUENCE; Schema: web; Owner: postgres
--

ALTER TABLE web.partner ALTER COLUMN id_partner ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME web.partner_id_partner_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16451)
-- Name: prodotto; Type: TABLE; Schema: web; Owner: postgres
--

CREATE TABLE web.prodotto (
    id_prodotto integer NOT NULL,
    nome_prodotto character varying NOT NULL,
    costo numeric NOT NULL,
    disponibile boolean DEFAULT false NOT NULL,
    provenienza integer DEFAULT 0 NOT NULL,
    tipo_prodotto_id integer NOT NULL,
    produttore_id integer NOT NULL,
    data_inserimento timestamp without time zone NOT NULL,
    data_modifica timestamp without time zone
);


ALTER TABLE web.prodotto OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16450)
-- Name: prodotto_id_prodotto_seq; Type: SEQUENCE; Schema: web; Owner: postgres
--

ALTER TABLE web.prodotto ALTER COLUMN id_prodotto ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME web.prodotto_id_prodotto_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16431)
-- Name: produttore; Type: TABLE; Schema: web; Owner: postgres
--

CREATE TABLE web.produttore (
    id_produttore integer NOT NULL,
    nome character varying NOT NULL,
    descrizione character varying,
    partner_id integer,
    tipo_categoria integer DEFAULT 0,
    n_dipendenti integer,
    fatturato_annuo numeric DEFAULT 0,
    sede_id integer NOT NULL,
    data_inserimento timestamp without time zone NOT NULL,
    data_modifica timestamp without time zone
);


ALTER TABLE web.produttore OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16430)
-- Name: produttore_id_produttore_seq; Type: SEQUENCE; Schema: web; Owner: postgres
--

ALTER TABLE web.produttore ALTER COLUMN id_produttore ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME web.produttore_id_produttore_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16480)
-- Name: ruolo; Type: TABLE; Schema: web; Owner: postgres
--

CREATE TABLE web.ruolo (
    id_ruolo integer NOT NULL,
    ruolo_utente character varying NOT NULL
);


ALTER TABLE web.ruolo OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16479)
-- Name: ruolo_id_ruolo_seq; Type: SEQUENCE; Schema: web; Owner: postgres
--

ALTER TABLE web.ruolo ALTER COLUMN id_ruolo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME web.ruolo_id_ruolo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16400)
-- Name: sede; Type: TABLE; Schema: web; Owner: postgres
--

CREATE TABLE web.sede (
    id_sede integer NOT NULL,
    indirizzo character varying NOT NULL,
    nazione character varying NOT NULL,
    data_costruzione date,
    valore_immobile numeric DEFAULT 0
);


ALTER TABLE web.sede OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16399)
-- Name: sede_id_sede_seq; Type: SEQUENCE; Schema: web; Owner: postgres
--

ALTER TABLE web.sede ALTER COLUMN id_sede ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME web.sede_id_sede_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16409)
-- Name: tipo_prodotto; Type: TABLE; Schema: web; Owner: postgres
--

CREATE TABLE web.tipo_prodotto (
    id_tipo integer NOT NULL,
    tipo_prodotto character varying NOT NULL
);


ALTER TABLE web.tipo_prodotto OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16408)
-- Name: tipo_prodotto_id_tipo_seq; Type: SEQUENCE; Schema: web; Owner: postgres
--

ALTER TABLE web.tipo_prodotto ALTER COLUMN id_tipo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME web.tipo_prodotto_id_tipo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16471)
-- Name: utente; Type: TABLE; Schema: web; Owner: postgres
--

CREATE TABLE web.utente (
    id_utente integer NOT NULL,
    username character varying NOT NULL,
    email character varying NOT NULL,
    password character varying NOT NULL,
    ruolo_id integer DEFAULT 1 NOT NULL
);


ALTER TABLE web.utente OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16470)
-- Name: utente_id_utente_seq; Type: SEQUENCE; Schema: web; Owner: postgres
--

ALTER TABLE web.utente ALTER COLUMN id_utente ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME web.utente_id_utente_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4678 (class 2606 OID 16424)
-- Name: partner partner_pk; Type: CONSTRAINT; Schema: web; Owner: postgres
--

ALTER TABLE ONLY web.partner
    ADD CONSTRAINT partner_pk PRIMARY KEY (id_partner);


--
-- TOC entry 4682 (class 2606 OID 16459)
-- Name: prodotto prodotto_pk; Type: CONSTRAINT; Schema: web; Owner: postgres
--

ALTER TABLE ONLY web.prodotto
    ADD CONSTRAINT prodotto_pk PRIMARY KEY (id_prodotto);


--
-- TOC entry 4680 (class 2606 OID 16439)
-- Name: produttore produttore_pk; Type: CONSTRAINT; Schema: web; Owner: postgres
--

ALTER TABLE ONLY web.produttore
    ADD CONSTRAINT produttore_pk PRIMARY KEY (id_produttore);


--
-- TOC entry 4686 (class 2606 OID 16486)
-- Name: ruolo ruolo_pk; Type: CONSTRAINT; Schema: web; Owner: postgres
--

ALTER TABLE ONLY web.ruolo
    ADD CONSTRAINT ruolo_pk PRIMARY KEY (id_ruolo);


--
-- TOC entry 4688 (class 2606 OID 16488)
-- Name: ruolo ruolo_unique; Type: CONSTRAINT; Schema: web; Owner: postgres
--

ALTER TABLE ONLY web.ruolo
    ADD CONSTRAINT ruolo_unique UNIQUE (ruolo_utente);


--
-- TOC entry 4674 (class 2606 OID 16407)
-- Name: sede sede_pk; Type: CONSTRAINT; Schema: web; Owner: postgres
--

ALTER TABLE ONLY web.sede
    ADD CONSTRAINT sede_pk PRIMARY KEY (id_sede);


--
-- TOC entry 4676 (class 2606 OID 16415)
-- Name: tipo_prodotto tipo_prodotto_pk; Type: CONSTRAINT; Schema: web; Owner: postgres
--

ALTER TABLE ONLY web.tipo_prodotto
    ADD CONSTRAINT tipo_prodotto_pk PRIMARY KEY (id_tipo);


--
-- TOC entry 4684 (class 2606 OID 16478)
-- Name: utente utente_pk; Type: CONSTRAINT; Schema: web; Owner: postgres
--

ALTER TABLE ONLY web.utente
    ADD CONSTRAINT utente_pk PRIMARY KEY (id_utente);


--
-- TOC entry 4689 (class 2606 OID 16425)
-- Name: partner partner_sede_fk; Type: FK CONSTRAINT; Schema: web; Owner: postgres
--

ALTER TABLE ONLY web.partner
    ADD CONSTRAINT partner_sede_fk FOREIGN KEY (sede_id) REFERENCES web.sede(id_sede);


--
-- TOC entry 4692 (class 2606 OID 16465)
-- Name: prodotto prodotto_produttore_fk; Type: FK CONSTRAINT; Schema: web; Owner: postgres
--

ALTER TABLE ONLY web.prodotto
    ADD CONSTRAINT prodotto_produttore_fk FOREIGN KEY (produttore_id) REFERENCES web.produttore(id_produttore);


--
-- TOC entry 4693 (class 2606 OID 16460)
-- Name: prodotto prodotto_tipo_prodotto_fk; Type: FK CONSTRAINT; Schema: web; Owner: postgres
--

ALTER TABLE ONLY web.prodotto
    ADD CONSTRAINT prodotto_tipo_prodotto_fk FOREIGN KEY (tipo_prodotto_id) REFERENCES web.tipo_prodotto(id_tipo);


--
-- TOC entry 4690 (class 2606 OID 16440)
-- Name: produttore produttore_partner_fk; Type: FK CONSTRAINT; Schema: web; Owner: postgres
--

ALTER TABLE ONLY web.produttore
    ADD CONSTRAINT produttore_partner_fk FOREIGN KEY (partner_id) REFERENCES web.partner(id_partner);


--
-- TOC entry 4691 (class 2606 OID 16445)
-- Name: produttore produttore_sede_fk; Type: FK CONSTRAINT; Schema: web; Owner: postgres
--

ALTER TABLE ONLY web.produttore
    ADD CONSTRAINT produttore_sede_fk FOREIGN KEY (sede_id) REFERENCES web.sede(id_sede);


-- Completed on 2025-03-19 18:56:57

--
-- PostgreSQL database dump complete
--

