name: CI

on:
  pull_request:
    branches:
      - dev    # Trigger action for PRs targeting the 'dev' branch
      - main   # Trigger action for PRs targeting the 'main' branch

jobs:
  build:
    runs-on: windows-latest  # Use the Windows environment for the job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout the code in the PR

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Set Java 17 as the required version

      - name: Install dependencies and run tests
        run: |
          .\mvnw clean install
          mvn test              # Run tests
